name: '🧑‍🏭'
on: [ push ]
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v') == true
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: actions/setup-go@v4.1.0
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true
      - run: |
          make check
      - run: |
          make release
      - uses: softprops/action-gh-release@v1
        with:
          body: 'Built at commit: ${{ github.sha }}'
          files: 'out/*'
